name: Tests unitaire
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches : [main]
jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name : Connexion à Docker 
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name : Install dependencies
        run : yarn
      - run: yarn test
      - run: yarn build
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{github.sha}}
          labels: ${{ steps.meta.outputs.labels }}
